### ISSUE TITLE
Frogger invisible on road

### ISSUE THREAD

**Issue by stazna01** [DirtyHairy/r77-firmware-ng#1]
I'm not sure if this is a stella 6 issue or an issue with the retron 77 and my settings, but I was playing my frogger bin file and frogger looks normal until frogger gets onto the road. At that point he becomes invisible. If I get him to the other side of the road he reappears. I tested this same rom on OpenEmu on my Mac (which is using Stella 3.9.3.3) and it works fine there.

**Comment by thrust26** [comment]
Thanks for reporting.

The problem is, that the R77 is skipping frames. We are working on it.

**Comment by DirtyHairy** [comment]
Thanks for the report. Do you have the same issue with the previous two beta releases, or does this affect only rc1?

**Comment by stazna01** [comment]
Unfortunately I never saw there were betas until I came across rc1, so I jumped directly to rc1. What would be most helpful to test? I'm assuming I can downgrade to either of the betas the same as I upgraded since it's just reflashing the SD. Is it more helpful to test one beta over the other?

**Comment by DirtyHairy** [comment]
Yes, just follow the instructions on the releases page. Beta 2 would be the one. As an alternative, you can give the following uImage a shot --- that should fix the issue. Just unzip it and replace the uImage on your SD with it.

[uImage.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/4278462/uImage.zip)

**Comment by DirtyHairy** [comment]
Fixed for good in 6.1.0.
