### ISSUE TITLE
ROMs always end up freezing with the latest builds?

### ISSUE THREAD

**Issue by divergentdeveloper** [DirtyHairy/r77-firmware-ng#10]
Hi! 

I've seen this reported on the atari age forum, and I can reproduce it 100% of the time on my Retron with the latest builds. The original Retron FW does not have this issue. 

I've tried version 6.6, 6.52 and 6.51 and they all seem to have this problem. I've reflashed and tried all the tips I saw in the forum like disabling the time machine, etc, and I always get the same result. 

It looks like it's working fine, and sometimes you can play for minutes without any issue, but every game I've tried ends up freezing. 

The ROM I use for these tests is MS pac man, I just let the attract mode play, and it always freezes up. I've seen it take as long as 13 minutes to freeze, sometimes it's only one minute. I've run the same ROM on the original FW for an hour without any freeze. 

Could it be that this problem has been present for a while and no one noticed it? I've done all the checks on my side and I can reproduce this 100% of the time on the brand new Retron I opened yesterday. 

I bought the R77 for this project so I don't mind doing tests or providing more info to solve this issue... and maybe I missed something in my tests and it's fine :)

**Comment by akator70** [comment]
I bought a Retron in December and have played it for at least 20 hours, including Ms. Pac-Man for 10-15 minutes.  I haven't had a single freeze or other issue in any game.

That you have tried several different versions makes me wonder if your Retron isn't defective.  The first one I received wouldn't boot at all and had to be exchanged.  The replacement is the one that has worked perfectly.

Have you tried different micro SD cards?  I've found lots of issues with other systems that rely on micro SD, often changing to a different card fixes whatever problem I'm having.

EDIT:  I've been using Stella 6.6.  I haven't had any problems with paddles, either.

**Comment by divergentdeveloper** [comment]
I've been wondering as well... could be that its defective, but since I see many others reporting the same issues, I wasn't sure. And I've played MS pac man for 10-15 minutes with no issues either... I can play it for a while without noticing it since games usually don't last longer than a few minutes. But for 20 hours, I would expect you'd have seen at least a few freezes. 

And the other thing that put some doubt in my mind, is that the original FW runs without any issues, except that it's a.... very limiting UI :)  

I tried with the "DONT_OVERCLOCK" option off and it still crashes, and what I saw didn't look like any frame drops i'd ever seen.. it was a mess on screen. It mentioned it was something to try for "buggy" hardware, which is possible in my case. It's just that the original FW runs so well with no issues. 

I just bought an harmony cart because it would circumvent the bad UI of the original FW, and will work in case I end up getting a real 2600 if the r77 isn't working out. 

I got this Retron from ebay so I can't return it like amazon if i think it's defective.. especially since it's not *really defective*, it's only the custom FW that has issues with it, and it's hard to prove it's the HW that's the problem. 

Oh and I am swapping between 3 SD cards of different brands. Same issues.

**Comment by akator70** [comment]
Judging from the AtariAge threads on the subject and all of the issues people have had, I don't think your experience is unusual.  My experience of it working perfectly may be the outlier.

My R77 works better than my MiSTer running the 7800/2600 core and had become my default choice for 2600.  The MiSTer has more compatibility issues than my R77, the frequent video timing issues trip up the MiSTer's HDMI output, and last I checked the MiSTer 7800/2600 core isn't really friendly with original paddles, even with USB adapters that work on everything else perfectly.

**Comment by divergentdeveloper** [comment]
Yeah that's the experience I heard about that got me to get it. :) it's only now that I have it that I see all of these folks having issues... They are very consistent though, so that's why I was thinking maybe an issue with the latests versions or that there are different versions of the HW...

I'll try games with the stock FW and see if everything is ok. Stella 6.6 is much better, but that would be an OK compromise for me and kind of salvage my investment. :)

**Comment by thrust26** [comment]
We think it might be a problem with the CPU. We overclocked it a bit to have no lags with modern ARM based games. The overclocking is still within the specs, but maybe there are CPUs with worse quality. 

Therefore the next release (6.7) will have an option to disable the overclocking. Maybe that solves your problem.

**Comment by DirtyHairy** [comment]
The option is already there 😏  --- that's `DONT_OVERCLOCK`. I have never been able to reproduce those crashes, but I'll give it a try. However, as it is a spurious issue that affects only some people I suspect that it is hardware related. The new firmware uses considerably more resource and more memory.

One thing worth trying might be a different power supply.

**Comment by thrust26** [comment]
@divergentdeveloper Did you already try `DONT_OVERCLOCK`?

**Comment by divergentdeveloper** [comment]
Yes , I tried DONT_OVERCLOCK. I think I saw dropped frames (ms pac man sprites didn't get cleared and ended up drawing on top of each other) and it still ended up crashing. 

It'a good idea to included it as a setting in the UI :) It will be way easier/faster for me when testing...

I suspect that even 1ghz "running hot" is too much for the flimsy R77s. I just saw that there's only one vent on the bottom of the thing, so that probably doesn't help either. 

I've seen the stock FW run nicely without any issues for a long time, so what I want to try next is to disable all the extra filters, time machine, etc that the new Stella offers and try to match the config of their original FW, and see if it doesn't crash.

**Comment by thrust26** [comment]
Did the DONT_OVERCLOCK extend the time until a crash? Regarding the ventilation, have you tried to run it upside down?

I wonder if the chip shortage caused Hyperkin to use 2nd grade chips. IIRC we had no reports earlier on. From when is your console, is it an orange one maybe?

**Comment by divergentdeveloper** [comment]
It didn't seem to extend the time before the crash, but that was already varying between 1 minute and 14 minutes so it's hard to tell.. It crashed after 2 and a half minutes, so it could have been a 1 minute crash that took 2 minutes with DONT_OVERCLOCK. :)

I haven't tried to run it upside down but that's definitely on my list since I saw that the vent was on the bottom :) Maybe I'll try with a fan pushing air down the vent too. I'll do some tests and report back here with the results. 

I have a black one, and I don't know how long it was in stock... I think you might be right with the 2nd grade chips, and it could be that they thought this was fine to put into production, because you dont see the crashes with the original FW. And I think they stopped producing them when they realized this :)

**Comment by divergentdeveloper** [comment]
Oh I just saw @DirtyHairy's note: Yes, I did try to switch power supplies. 

I'm pretty sure too that it's hardware related.

**Comment by divergentdeveloper** [comment]
![DONTOVERCLOCK](https://user-images.githubusercontent.com/111537887/185666429-e0ce23a5-82d7-4894-9079-90e852c19904.PNG)

I did some testing with the unit upside down, with a fan, without all the tv effects, phosphor, etc. and it still crashes. 

I tried with DONT_OVERCLOCK (see attached pic, I hope I did this right) and I still get the same result. 

Sadly, it really looks like a HW issue. These batches of r77's can't seem to be able to run this FW. It's really puzzling to me since the stock FW with Stella 3.5.2 runs without any issues, but there is probably more going on with v6.6 than I can see on screen... 

Unless anyone has any other ideas to try, I think I'll be stuck with the stock FW and wait for my Harmony card, unless I can find another r77 that doesn't have this issue... but that seems unlikely/difficult as they've seemed to have stopped producing them.

**Comment by thrust26** [comment]
First you might want to try to switch the renderer to "Software" (you have to switch to advanced settings to do so). That disables using the GPU's hardware acceleration.

If that still doesn't help, you could try one of the first community editions (some where on AtariAge) which was based on an older Stella version (3.51 IIRC). This should emulate identical with the stock version.

**Comment by sa666666** [comment]
The very last community edition based on the old Stella was 3.9.3.  So that's the one to look for.

**Comment by divergentdeveloper** [comment]
Good idea! Stock probably doesn't OpenGLES, I will try that... 

Oh I was looking for that! I thought I had seen it but couldn't find it on Github so I thought I had imagined it... I will definitely look for it as it would give me the nice UI of the CFW

**Comment by divergentdeveloper** [comment]
@sa666666 thanks so much! I will hunt this down

**Comment by divergentdeveloper** [comment]
Seems that the OP removed the links when the new version was released, I don't see any links available to get it now... :(

**Comment by thrust26** [comment]
Wayback Machine to the rescue:
https://www.dropbox.com/s/q2965rrzpo0jq2e/sdcard.remo.20181120-1353CB.zip?dl=0

I think that is the latest version. You have to search for the old AtariAge links, before the latest migration.
http://atariage.com/forums/topic/281462-retron-77-community-build-image/

**Comment by divergentdeveloper** [comment]
@thrust26  niiice! many thanks I had not found that one! It's probably v.3.9.3 that I was looking for. 

I also found "sdcard.remo.20190119-1727.test" in the attachments of the thread, which was v3.9.4 and I got to test it during lunch and.... no crash! It ran for an hour without any issues. I will test this more extensively but so far this is great news for me :)

I will also try 6.6 with the software rendering like you suggested.

**Comment by divergentdeveloper** [comment]
Crashes on 6.6 with software rendering and DONT_OVERCLOCK

**Comment by DirtyHairy** [comment]
How adventurous are you feeling? In order to drill down to the source of those crashes we'd need to run Stella (possibly built with debug symbols) from the command line and capture the output. This either requires a supported ethernet dongle and a SSH connection or a serial connection. The serial connection arguably is easier to set up, but it requires soldering a few wires to unused pads on the R77 board and a UART-to-USB dongle (a few bucks on amazon). If you want to go either way I'll be happy to assist you.

**Comment by divergentdeveloper** [comment]
If time is not an issue, I might be adventurous enough for either option :) 

I might actually have one of those ethernet dongles, just saw the info on which ones would work and how to try it. I'll give it a go this weekend... 

Also, reading the documentation, it seems that DONT_OVERCLOCK is for developer mode only. I don't think I had the console in that mode so I'll also try that again.

**Comment by divergentdeveloper** [comment]
It took 17 minutes for MS pac man to crash, but it went back to the launcher this time, with developer mode enabled. Launcher is operational afterwards... Very interesting! I've seen hundreds of hangs so far, but never did it make it back to the launcher.

**Comment by thrust26** [comment]
That was the latest version with "Software" renderer, right?

**Comment by DirtyHairy** [comment]
Interesting indeed, but as I said, guesswork is not gonna take us anywhere.

@divergentdeveloper If you would be able to get a shell on the device this would be great. Ethernet and SSH are more hassle to set up, but you can use `scp` to transfer files once you've got it working (i.e. to copy and run a debug build of Stella). Serial is easier to set up if you are comfortable with modifying your device, but you can't transfer files over the serial connection (easily). You can find instructions for accessing the UART here: https://github.com/stella-emu/stella/wiki/Retron-77

**Comment by divergentdeveloper** [comment]
@thrust26 Exactly, with time machine off, all TV effects off... I could see alot of frames dropped, like the machine was struggling to keep up. 

@DirtyHairy Yes, that's my next step :) I just wanted to make sure I tried the DONT_OVERCLOCK correctly and still got a crash. 

My USB to UART dongle is arriving tomorrow, I'll let you know when I have a shell going. It seems the easiest option and not too above my skill level.. I'm guessing I can just swap the SD card back and forth to transfer files when needed? That's not too much trouble.

**Comment by thrust26** [comment]
Still speculating, but that doesn't sound good. Ms. Pac Man doesn't require that much CPU performance, it should run well at 1 GHz. To me it seems like the CPU is already overheating and maybe throttling (but then it should not crash).

@DirtyHairy Do you know if the CPU is permanently running at the given frequency or if it uses DVFS?

**Comment by divergentdeveloper** [comment]
@thrust26 It doesn't look good either, if you want to see. I made a little 3.5.4 vs 6.6 comparison video:
https://www.youtube.com/watch?v=5ABeCHBX6OM

It seems to run slower as well.

**Comment by DirtyHairy** [comment]
> @DirtyHairy Do you know if the CPU is permanently running at the given frequency or if it uses DVFS?

No, there is no governor, the CPU runs permanently at the configured speed. If it throttles then this must be the chip itself.

**Comment by DirtyHairy** [comment]
> My USB to UART dongle is arriving tomorrow, I'll let you know when I have a shell going. It seems the easiest option and not too above my skill level.. I'm guessing I can just swap the SD card back and forth to transfer files when needed? That's not too much trouble. 

Yep, that will work. Thanks a lot!

**Comment by thrust26** [comment]
> > @DirtyHairy Do you know if the CPU is permanently running at the given frequency or if it uses DVFS?
> 
> No, there is no governor, the CPU runs permanently at the configured speed. If it throttles then this must be the chip itself.

That doesn't leave many options, does it? With constant frequency, the CPU is not stressed more in Stella 6.x than 3.x, hardware acceleration is not used in both, so its not the GPU too. What's left? RAM?

**Comment by divergentdeveloper** [comment]
Got a USB2UART device that had an issue so spent most of my time today debugging that! Now that it works I still don't have a shell connection, but it's probably my bad solder using the included wires. 

I'll clean up and try again tomorrow, I've got some better wires coming in as well.

**Comment by DirtyHairy** [comment]
Keep in mind that you need to cross RX and TX, i.e. RX goes to TX and vice versa.

**Comment by divergentdeveloper** [comment]
![shell](https://user-images.githubusercontent.com/111537887/186155698-024d64ed-0260-4dfc-a37d-8e53efd3edf6.PNG)

Yes! That was it! Seems my soldering was fine :) I had completely forgot about this... 

Many many thanks! I'm ready for the next steps then :)

**Comment by DirtyHairy** [comment]
Nice 😏 

Now, how to proceed. When the R77 starts up it launches a `dumper` process, and this process in turn spawns `stella`. So, what we need to do is kill the dumper and stella. After this is done we are free to start stella ourselves on the terminal and observe its `stdout` and `stderr` while it runs and crashes.

First do a

```
# ps aux
```

The process list should include stella and the dumper. After that, do

```
# killall -9 dumper
# killall -9 stella
```

It is fine if the second command fails, the child process should die with `dumper` anyway, I just added the second command to be 100% sure. Check the process list again; the two processes should be gone now. At this point you can launch stella manually by doing

```
# stella /mnt/path/to/rom
```

Note that the SD card is mounted on `/mnt`, so `/path/to/rom` refers to the path to the (Ms. Pacman) ROM on your SD card. This will start stella and launch the ROM. After stella has crashed, the first thing is to check whether Linux is still running, i.e. whether you can still type commands. If it does, please paste the output of Stella here and also paste the output of doing

```
# dmesg
```

If Linux itself has crashed, well, that's information, too 😛 Thank you again for your help.

**Comment by divergentdeveloper** [comment]
Success! 

When it crashed the first time, with software rendering, no overclock:
```
malloc_consolidate(): unaligned fastbin chunk detected
Aborted
```
I also tried having it crash with OpenGLES right after, no overclock, and got:
`Segmentation fault`

I've got the output of dmesg in a text file here:
[dmesg.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9411764/dmesg.txt)

**Comment by DirtyHairy** [comment]
Thanks alot. Nothing interesting in that dmesg. The two crashes hint at memory corruption. This may be caused by either bad hardware or a bug somewhere in the stack. Let me prepare a debug build that will give a readable backtrace. In the meantime, could you retry a few more times and check how the error message fluctuates? I honestly don't think this has anything to do with software vs. hardware rendering.

**Comment by divergentdeveloper** [comment]
Just got a new one with a lot more meat, here it is attached. I'll try to
capture a few here today while working, and post them here if they are new
and interesting.

I agree with the software vs hardware, it's just my habit of
mentioning what config I changed in the tickets. :) I put back the original
config with OpenGLES, TV effects and everything since it crashes more
frequently this way. I'll probably put overclock back since I've had
half-hour runs without crashing and that's not what we're looking for ;)

[crash.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9416271/crash.txt)

**Comment by divergentdeveloper** [comment]
Another interesting one: it didn't crash, it's still running but I've just got warnings that ends with 
`[ 1184.929432] Fixing recursive fault but reboot is needed!`
[warning.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9416376/warning.txt)

**Comment by divergentdeveloper** [comment]
[crash2.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9416387/crash2.txt)

and it crashed shortly after :)

**Comment by divergentdeveloper** [comment]
This third crash is almost indentical the first crash.txt
[crash3.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9417033/crash3.txt)

**Comment by thrust26** [comment]
crash2 lists a "hard LOCKUP on cpu 0". How can that happen?

**Comment by divergentdeveloper** [comment]
A few more:

[crash4.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9417506/crash4.txt)
[crash5.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9417508/crash5.txt)
[crash6.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9417509/crash6.txt)
[crash7.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9417511/crash7.txt)

**Comment by thrust26** [comment]
Another **very** vague idea: Can you try a different, stronger power supply? How is the one you are using defined?

Or maybe @DirtyHairy already knows what is going on.

@DirtyHairy Do we know for sure that the original firmware is running at 1GHz?

**Comment by divergentdeveloper** [comment]
@thrust26 Sure. I've tried 3 so far but I don't have logs of those crashes. I can do a test run my best power supply and see the result :) Current one is a 2.1A generic adapter.

**Comment by thrust26** [comment]
> @thrust26 Sure. I've tried 3 so far but I don't have logs of those crashes. I can do a test run my best power supply and see the result :) Current one is a 2.1A generic adapter.

Thanks, but if you already have tested multiple adapters, I am pretty sure my idea is wrong.

**Comment by DirtyHairy** [comment]
Thanks alot! I am afraid this is pretty conclusive, no need for running a debug build: this is either a kernel bug or faulty hardware. None of these errors in dmesg can be caused by userspace alone, and this rules out memory corruption in Stella. As only some consoles are affected I am 99% positive that hardware is the issue, probably SDRAM.

I'll try to build a version that clocks RAM at 480 MHz (instead of 624 MHz) to see whether this works any better.

> @DirtyHairy Do we know for sure that the original firmware is running at 1GHz?

Yes 😏 Besides, that option does not set the clock to 1.2 GHz explicitly, but just keeps it the way it was at boot.

**Comment by thrust26** [comment]
> I'll try to build a version that clocks RAM at 480 MHz (instead of 624 MHz) to see whether this works any better.

Did you increase the RAM speed too? Else the original firmware should have similar problems, no?

**Comment by DirtyHairy** [comment]
> Did you increase the RAM speed too? Else the original firmware should have similar problems, no?

No, I think this is bad hardware. Maybe they changed the RAM chips. It is very possible that the new firmware uses more RAM bandwidth, and maybe this exposes the issue.

@divergentdeveloper I have a version of the bootloader that reduces the DRAM clock to 480 MHz. Do you have access to a linux machine and feel confident enough to write it to the SD card with `dd` (I'll give you the specifics), or should I prepare a full SD card image?

**Comment by divergentdeveloper** [comment]
@DirtyHairy I don't have a linux machine handy, but shouldn't be a problem if I did :) 

If you've got the setup to prep the SD image and it's not too much trouble, I think that'd be the easiest/fastest.. If not, I can get a VM up and running later this week and do the copy. 

Unless you know of a windows app that lets you browse and write to linux FS? Just used one today for something but it's read-only, and the other one I saw was commercial and cost money.

**Comment by DirtyHairy** [comment]
No worries, try the attached image, that should do the trick (you'll have to unzip it before 😏 ). The catch here is that the bootloader is not a file anywhere, but instead resides in the first sectors of the SD card. The H3 CPU has a builtin ROM that loads and runs it from there. So, you'd need to use `dd` to write the loader to the raw SD device.

If the device still crashes paste the messages. I am particularly interested in the line that reads "ddr frequency ..." --- that should be 480MHz now. I haven't found a straightforward way to get that from a healthy system, but I found that doing `cat /proc/sram` will cause a kernel oops similar to those caused by Stella that dumps the same information.

If you are looking for a way to read ext filesystems on windows: I have been using Paragon on MacOS with good results, and I am pretty sure they have windows drivers, too. However, they are commercial and cost money.

[sdcard.img.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9418584/sdcard.img.zip)

**Comment by divergentdeveloper** [comment]
I was expecting to have tons of messages to paste. but so far I haven't been able to crash it. :) I've run it for an hour and it's stable with no issues. 

Just to compare, I had never seen 6.6 run more than 15 minutes before this build. 

I'll keep at it but it really looks like you found the culprit

**Comment by divergentdeveloper** [comment]
Finally got one!

[ 6340.710053] sunxi oops: ddr frequency: 480 MH
[newcrash.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9429309/newcrash.txt)

**Comment by thrust26** [comment]
@DirtyHairy All the crash reports show a DDR frequency of just 480 MHz. I suppose this information is not correct?

**Comment by thrust26** [comment]
> Finally got one!
> 
> [ 6340.710053] sunxi oops: ddr frequency: 480 MH [newcrash.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9429309/newcrash.txt)

Yes, looks like the RAM is faulty. How long did it take?

**Comment by thrust26** [comment]
> I was expecting to have tons of messages to paste. but so far I haven't been able to crash it. :) I've run it for an hour and it's stable with no issues.

I suppose you are still testing with Ms. Pac-Man? Try one of the modern ARM games, like Galagon, Mappy and especially Robotwar-2684. These stress the CPU much more and I suppose the RAM too. And enable the Time Machine for more stress.

**Comment by DirtyHairy** [comment]
> @DirtyHairy All the crash reports show a DDR frequency of just 480 MHz. I suppose this information is not correct?

```
[  597.116366] sunxi oops: cpu frequency: 1200 MHz
[  597.120637] sunxi oops: ddr frequency: 624 MHz
[  597.120637] sunxi oops: gpu frequency: 252 MHz
[  597.120637] sunxi oops: cpu temperature: 58
```

Seems correct to me 😏

**Comment by DirtyHairy** [comment]
@divergentdeveloper Thank's alot! Seems indeed like bad RAM: I'll prepare another image with 320MHz later, let's see how that goes.

**Comment by DirtyHairy** [comment]
> > I was expecting to have tons of messages to paste. but so far I haven't been able to crash it. :) I've run it for an hour and it's stable with no issues.
> 
> I suppose you are still testing with Ms. Pac-Man? Try one of the modern ARM games, like Galagon, Mappy and especially Robotwar-2684. These stress the CPU much more and I suppose the RAM too. And enable the Time Machine for more stress.

Also, try the Stay Frosty 2 titlescreen and check how many snowmen you see (should be two) 😏 I am a bit afraid that the GPU may not be able to keep 60FPS at lower DRAM clock values, and the symptom would be dropped frames.

**Comment by thrust26** [comment]
Here is the ROM, just in case...
[SF2_20131217_RC8_NTSC.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9432598/SF2_20131217_RC8_NTSC.zip)

**Comment by divergentdeveloper** [comment]
@thrust26 A little over 2 hours with MS Pac-man. And now I always test with time machine enabled to stress it more. :)

I checked and I don't have those ROMs "Galagon, Mappy and especially Robotwar-2684". Just saw there are demos I can try, and I didn't know about those homebrews so that's a fun discovery! Thanks for the SF2 ROM, I'll try that too. 

MS pac-man took 2 hours to crash at 480mhz so I'm guessing the new build with 320mhz will take even longer, and it's not stressing the machine enough to get dropped frames. :) 

@DirtyHairy Can't wait to try the new build! I have some time on the weekend to make some test runs.

**Comment by DirtyHairy** [comment]
Here's two more:

[sdcard_312mhz.img.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9436155/sdcard_312mhz.img.zip)
[sdcard_408mhz.img.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9436157/sdcard_408mhz.img.zip)

**Comment by DirtyHairy** [comment]
> I tried with DONT_OVERCLOCK (see attached pic, I hope I did this right) and I still get the same result.

Oh, btw, I overlooked this, this is indeed wrong --- the line needs to read

```
DONT_OVERCLOCK=1
```

😏

**Comment by divergentdeveloper** [comment]
@DirtyHairy Humm I see one snowman and two fireballs... However, that's what I see in the other videos of it on youtube? I saw one with one fireball that seemed at 30fps so perhaps that's one you meant?
![stay frosty](https://user-images.githubusercontent.com/111537887/187011967-301150ef-1fa6-4090-9558-c739f3ded497.PNG)
At 408mhz I see both and the game is running similar to what I see on other videos. And with overclock :) Seems I never did try without CPU overclock.

**Comment by divergentdeveloper** [comment]
Finally got one with Galagon at 408mhz:
[galagon-408mhz.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9437295/galagon-408mhz.txt)

**Comment by DirtyHairy** [comment]
Sorry, yeah, I meant two fireballs, one snowman, that's the correct number of things 😏

**Comment by DirtyHairy** [comment]
Let's see how 312 MHz does, but I guess this is the best we can get: significantly reduce the amount of crashes without completely eliminating them. I'll open a thread on AAge later this weekend with the modified images to get a few more data points, and then I guess I'll add a few notes to the documentation and update 6.6 (and the future 6.7) with additional SD card images.

**Comment by divergentdeveloper** [comment]
312 mhz is next to try on my list. :) Good idea to open a thread to get more data, as it now can take hours to get one or two.

I was thinking about this and I agree, it's the best that can be done with these faulty consoles. It might be good enough for some people to salvage their investment a little. It now can take a while and some demanding games to see a crash, and I haven't noticed any frame drops when comparing to original console footage. 

You might not even get a crash on your gaming session if you switch games every few minutes and mostly play the early titles.

**Comment by rhester72** [comment]
Isn't there a way to display FPS in real time for easier observation if rate dips are occurring?

**Comment by divergentdeveloper** [comment]
Good point, I didn't see an option explicitly for this but I think I saw an option to "display info" that I've never tried, and I see there's a keyboard shortcut. I'll try those!

**Comment by thrust26** [comment]
You can also enable it in Developer Settings (Advanced Setting mode).

**Comment by DirtyHairy** [comment]
Yeah, you can check the info display, the value you are looking for is "xx FPS @ 100% speed" --- if it is lower than the FPS value in the number of scanlines you are skipping frames.

@divergentdeveloper Could you also check the temperature of the DRAM chip by touching it? [The internet](https://linux-sunxi.org/Xunlong_Orange_Pi_PC) suggest that DRAM issues may be alleviated by adding a heatsink to the RAM chip.

**Comment by divergentdeveloper** [comment]
Stay Frosty 2 isn't playable at 312 mhz, there are tons of stuff missing from the screen even after disabling most enhancements, although Stella reports 60fps without issues. :) 

I'd say part of the DRAM chip is surprisingly hot after a run of SF2. I don't have a spare mini heatsink but I think it would help. 

Crashed with a 
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by DirtyHairy** [comment]
> although Stella reports 60fps without issues. :)

Ah, sorry, my bad, I just rechecked the code, the FPS that are displayed by Stella refer to the number of generated frames, not to those that are actually rendered. So, from the frequencies I chose, 408MHz seems to be as low as we can go before the GPU can't keep up.

@divergentdeveloper Do you have some makeshift way of cooling the DRAM to see whether that helps with the crashes? Maybe an external fan, or a cold pack in a cloth or something?

**Comment by thrust26** [comment]
@DirtyHairy It might help increasing the MHZ a little bit. But judging from the Orange Pi link and the rather little differences with and without a heatsink (up to 96 MHZ), I doubt additional cooling it will bring us back into the 600 MHz range. 

BTW: Did you check if the calibration code is patched already?

**Comment by divergentdeveloper** [comment]
> Do you have some makeshift way of cooling the DRAM to see whether that helps with the crashes? Maybe an external fan, or a cold pack in a cloth or something?

@DirtyHairy I do. :) I just setup an external fan and running "Stay Frosty 2" ironically. Let's see how this goes...

**Comment by DirtyHairy** [comment]
The irony... 😏 Looking forward to seeing what happens.

**Comment by divergentdeveloper** [comment]
It ran for 90 minutes without issues. :) 

I'm going to let it cool and try a run at 408 with the fan.

**Comment by divergentdeveloper** [comment]
> I'm going to let it cool and try a run at 408 with the fan.

Around 60 minutes...

**Comment by DirtyHairy** [comment]
Crashed again after 60 minutes, right? Well, to wrap things up, I'll prepare a new firmware image that includes a `lima-memtester` , at different DRAM clocks. I'll post that here and on AAge, may take a few days though.

> BTW: Did you check if the calibration code is patched already?

What code are you referring to?

**Comment by divergentdeveloper** [comment]
@DirtyHairy Exactly :)

**Comment by thrust26** [comment]
> > BTW: Did you check if the calibration code is patched already?
> 
> What code are you referring to?

I could be wrong, but [this](https://linux-sunxi.narkive.com/SIXw3m08/patch-0-6-arm-sunxi-introduce-allwinner-h3-support) discussion seems to imply that there is or was a bug in the code:

> Currently U-Boot v2016.01-rc2 fails the lima-memtester check unless
the DRAM clock speed is reduced to 456 MHz on my Orange Pi PC. But
if I use the boot0 bootloader to boot the same kernel image
(uImage-3.4-sun8i-h3-lima-memtester), then the test works fine.
This means that there must be still something wrong with the H3
DRAM init code in U-Boot, or maybe some clocks are wrong.

**Comment by DirtyHairy** [comment]
Good find, that slipped me. Unfortunately, the patch is already applied.

**Comment by DirtyHairy** [comment]
OK, here is a final test. The attached three imaged incorporate `lima-memtester`. If you create a file called `memtest` at the root of your SD card the R77 will not start Stella, but instead boot into the memtester. The tester will display a spinning [companion cube](https://theportalwiki.com/wiki/Weighted_Companion_Cube) on a gray background. The assumption is that it locks up or becomes garbled / discolored when DRAM behaves unstable.

@divergentdeveloper could you try the memtester for those three different clocks on your console and report what happens?

[sdcard-408mhz.bin.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9491670/sdcard-408mhz.bin.zip)
[sdcard-480mhz.bin.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9491677/sdcard-480mhz.bin.zip)
[sdcard-504mhz.bin.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9491680/sdcard-504mhz.bin.zip)

**Comment by thrust26** [comment]
Nice!

@DirtyHairy Have you tried yourself? Maybe we should find out how good our own consoles are. And then we probably need higher MHz variants.

**Comment by DirtyHairy** [comment]
Mine is fine at all speeds 😏

**Comment by DirtyHairy** [comment]
(up to 624MHz)

**Comment by DirtyHairy** [comment]
Here's the 624MHz image in case you want to try:

[sdcard.img.zip](https://github.com/DirtyHairy/r77-firmware-ng/files/9491725/sdcard.img.zip)

**Comment by thrust26** [comment]
Maybe I will. Does your RAM get hot too?

**Comment by DirtyHairy** [comment]
Warm, yes, not what I would call hot.

**Comment by thrust26** [comment]
Is that possible? That one RAM gets hot and one does not? Under the same conditions?

**Comment by DirtyHairy** [comment]
Different chips 🤷‍♂️ Besides, what is hot for @divergentdeveloper might not be hot to me 😏

**Comment by thrust26** [comment]
Could the chips be handled differently by the OS? Based on some kind of detection or so?

**Comment by DirtyHairy** [comment]
No, afaik there is no way to identify the specific DRAM chip.

**Comment by divergentdeveloper** [comment]
@DirtyHairy sure! will report back soon with the results :)

**Comment by divergentdeveloper** [comment]
[crash 502mhz.txt](https://github.com/DirtyHairy/r77-firmware-ng/files/9521897/crash.502mhz.txt)
![image](https://user-images.githubusercontent.com/111537887/188992234-b0f9f606-db9e-4928-9ff4-4c417027006f.png)

It's a very quick way to make it crash :) I assume the red background behind the companion cube is not a good sign?

**Comment by divergentdeveloper** [comment]
@DirtyHairy It starts normally with a grey background, but eventually turns to a slowly flashing red, and crashes. I don't see any output until the crash... And like the other images you made, it crashes way faster at high clock speeds. 

I thought there would be some output or a file to grab after, but I think the red background is what you were expecting :) I don't see anything new or different in the oops logs, I attached one in the above post. 

Sometimes it locks up without any output too, companion cube frozen over the red background... 

![image](https://user-images.githubusercontent.com/111537887/189233275-92be6c64-da0e-4d7d-9371-5cb5d5059248.png)

**Comment by DirtyHairy** [comment]
Sorry for the late repy. Yeah, the companion cube on a red background is a dead companion cube 😏 Thanks for the testing. The memtester does not help with resolving this issue, but at least we know that we can now reliably pinpoint it.

I'll post the images to AAge to get some more data how widespread this issue is, and I'll keep the memtester in the firmware and will provide images with downclocked DRAM. There aren't many options apart from that, but I'll investigate whether we can detect the oops on next boot and show a message.

**Comment by thrust26** [comment]
I think informing the people who are affected and providing the necessary tools is about the best we can do here.  Unfortunately. 😒 

Also we should provide the latest "old" community (3.9..4) build besides our normal R77 releases. And maybe some description of the problem which we can refer to.

**Comment by DirtyHairy** [comment]
I've posted on AtariAge: https://forums.atariage.com/topic/340990-buggy-r77s-crashing-with-stella-6x/

**Comment by divergentdeveloper** [comment]
@DirtyHairy No worries on the delay. I'm slow myself since my hands are usually full of paint these days... thanks for posting! I'll follow the posting in case stuff happens. 

@thrust26 I think that's a very good thing :) Not knowing for sure that there are faulty units out there when you ty the community build kind of sucks, and Hyperkin didn't really advertise it. I think it was worth the investigation :) 

I've been wanting to try this "close with comment" feature and I was about to write what @thrust26 just wrote. I think it's the best thing that can be done and I propose we close this one and follow the AtariAge thread in case some peeps chime in.
