### ISSUE TITLE
Black screen with no games directory and no cart in slot

### ISSUE THREAD

**Issue by fluxit1** [DirtyHairy/r77-firmware-ng#2]
If the user doesn't create a /games directory, the R77 will work with physical cartridges, but instead of showing the launcher will simply generate a black screen(HDMI signal present) with the cart slot empty on the 6.1.1 firmware.

**Comment by thrust26** [comment]
I will create a Stella issue for this instead.

https://github.com/stella-emu/stella/issues/638
