### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by washac** [DirtyHairy/r77-firmware-ng#6]
I have changed Brightness, Contrast and Gamma settings, and then OK out of the settings, while the Retron is turned on all is OK but If I switch the Retron Off and On again the settings have reverted back to the default.
Maybe other settings are also doing not that I have changed anything else.

**Comment by thrust26** [comment]
Which version of Stella for R77 are you using?

Please try other settings too (e.g. volume or TV effects). Same problem?

**Comment by washac** [comment]
Version is Stella 6.5.2
Settings I tried......
DISPLAY - Overscan settings held OK
TV EFFECTS - Held OK
VOLUME Change held OK
PALLETS - Contrast, Brightness and Gamma changes did not hold after reboot.

**Comment by DirtyHairy** [comment]
Indeed, this is a Stella bug, thanks for the report. I have opened a Stella bug: https://github.com/stella-emu/stella/issues/787

**Comment by DirtyHairy** [comment]
Fixed.
