### ISSUE TITLE
Oops closed in error settings not saving

### ISSUE THREAD

**Issue by washac** [DirtyHairy/r77-firmware-ng#7]
I have changed Brightness, Contrast and Gamma settings, and then OK out of the settings, while the Retron is turned on all is OK but If I switch the Retron Off and On again the settings have reverted back to the default.
Maybe other settings are also doing not that I have changed anything else.

Version is Stella 6.5.2
Settings I tried......
DISPLAY - Overscan settings held OK
TV EFFECTS - Held OK
VOLUME Change held OK
PALLETS - Contrast, Brightness and Gamma changes did not hold after reboot.

**Comment by DirtyHairy** [comment]
Please stick with one issue --- you can simply reopen it if you accidentally closed it 😏
