### ISSUE TITLE
Paddles “sticky ness” with 2600-adapter

### ISSUE THREAD

**Issue by CaptMoore** [DirtyHairy/r77-firmware-ng#8]
The issue I am having with both paddles is a “dead spot” near the left side of the game screen where the paddle bar pauses before continuing to scroll left. This is when I try to play Atari’s breakout image. 

At first I thought it was an issue with the paddles, but then using Stella on my iMac, the same paddles with the same adapter didn’t display this, they were smooth side to side without the “stop point” near (but not fully) on the left side.

It has been strongly suggested that it is related to a Linux specific issue, which has already been solved, at:  https://stella-emu.github.io/evdev-joystick.tar.xz, but this is only for standalone Linux, and not the R77 port.

Could this utility program be implemented for the R77 firmware, either as a helper app, or part of the r77 version of stella?

I would love to have this paddle issue fixed, if it is possible.

**Comment by DirtyHairy** [comment]
Fixed in 6.6.0
